### ISSUE TITLE
Add Unit Testing

### ISSUE THREAD

**Issue by ernest-okot** [sparkplug/momoapi-node#8]
**Problem**

Most of the code currently in master is not tested. This means it will be hard for to detect when this library starts to fail.

**Solution**

To ensure that the library behaves as expected, we need to add tests. Since we are using axios, we can use something like [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter) to create mock server responses and then proceed to add unit tests

**Tasks**

- [x] setup axios mock adapter
- [x] add unit tests for collections
- [x] add unit tests for users
